{
    "name": "Odoo Banking CRM",
    "summary": "Add-on for banking-specific CRM functionalities in Odoo",
    "version": "17.0.1.0.0",
    "category": "Customer Relationship Management",
    "depends": [
        "base",
        "contacts",
        "crm"
    ],
    "data": [
        "data/ir_model_data.xml",
        "security/ir_model_access.xml",
        "security/banking_security.xml",
        "security/banking_security_rules.xml",
        "security/ir.model.access.csv",
        "views/banking_crm_customer_actions.xml",
        "views/crm_lead_views.xml",
        "views/res_partner_views.xml",
        "views/banking_crm_customer_filter.xml",
        "views/banking_account_views.xml",
        "views/banking_card_views.xml",
        "views/banking_loan_views.xml",
        "views/banking_loan_document_views.xml",
        "views/banking_account_transaction_views.xml",
        "views/banking_ticket_views.xml",
        "views/banking_dashboard_views.xml",
        "views/loan_analysis_report_views.xml",
        "views/ticket_analysis_report_views.xml",
        "views/banking_loan_application_views.xml",
        "views/banking_conditions_precedent_views.xml",
        "views/banking_guarantor_views.xml",
        "views/banking_overall_dashboard_views.xml",
        "views/banking_dashboard_graphs.xml",
        "data/banking_crm_demo_data.xml",
        "data/banking_crm_additional_demo_data.xml",
        "data/banking_crm_seed_data.xml",
        "data/banking_crm_users_data.xml",
        "views/banking_crm_menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "/odoo_banking_crm/static/src/css/custom_styles.css",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": "LGPL-3",
    "post_init_hook": "post_init_hook",
}
