from . import res_partner
from . import banking_account
from . import banking_loan
from . import crm_lead
from . import banking_loan_document
from . import banking_account_transaction
from . import banking_ticket
from . import loan_analysis_report
from . import ticket_analysis_report
from . import banking_loan_application
from . import banking_conditions_precedent
from . import banking_guarantor
from . import banking_overall_dashboard
from . import res_partner_extension
from . import banking_card
